-- MySQL Script generated by MySQL Workbench
-- 10/07/16 11:37:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pk10
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pk10
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pk10` DEFAULT CHARACTER SET utf8 ;
USE `pk10` ;

-- -----------------------------------------------------
-- Table `pk10`.`betinit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`betinit` (
  `id` INT(11) NOT NULL,
  `g_name` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `rate` DOUBLE NULL DEFAULT NULL,
  `money_limit` INT(11) NULL DEFAULT NULL,
  `init_money` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`goods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `goodname` VARCHAR(255) NULL DEFAULT NULL COMMENT '????',
  `price` FLOAT NULL DEFAULT NULL COMMENT '????',
  `goodsimg` VARCHAR(255) NULL DEFAULT NULL COMMENT '?????',
  `goodsnum` INT(11) NULL DEFAULT NULL COMMENT '????',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '???';


-- -----------------------------------------------------
-- Table `pk10`.`lotteryhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`lotteryhistory` (
  `id` INT(11) NOT NULL COMMENT '期数 当前为第几期',
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '开奖时间',
  `lotterynums` CHAR(29) NULL DEFAULT NULL COMMENT '开奖结果，直接储存10位数字 用‘，’隔开',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '开奖历史表';


-- -----------------------------------------------------
-- Table `pk10`.`money_add_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`money_add_record` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `add_time` DATETIME NULL DEFAULT NULL,
  `add_money` DOUBLE NOT NULL,
  `add_agent_name` VARCHAR(45) NULL DEFAULT NULL,
  `add_agent_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`notice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '??ID',
  `content` VARCHAR(12000) NULL DEFAULT NULL COMMENT '通知内容',
  `title` VARCHAR(45) NULL DEFAULT NULL COMMENT '通知标题',
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '通知创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = '系统通知表';


-- -----------------------------------------------------
-- Table `pk10`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '??ID',
  `user` VARCHAR(255) NULL DEFAULT NULL COMMENT '????',
  `price` DOUBLE NULL DEFAULT NULL COMMENT '????',
  `status` VARCHAR(45) NULL DEFAULT NULL COMMENT '????',
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '????',
  `userinfo_openid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_userinfo1_idx` (`userinfo_openid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '???';


-- -----------------------------------------------------
-- Table `pk10`.`orders_has_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`orders_has_goods` (
  `order_id` INT(11) NOT NULL,
  `goods_id` INT(11) NOT NULL,
  INDEX `fk_order_has_goods_goods1_idx` (`goods_id` ASC),
  INDEX `fk_order_has_goods_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_goods_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `pk10`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_goods_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `pk10`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`test` (
  `a` CHAR(1) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`tokenconfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`tokenconfig` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tokenurl` VARCHAR(200) NULL DEFAULT NULL COMMENT '微信相关 — 废弃',
  `appid` CHAR(18) NULL DEFAULT NULL COMMENT '微信相关 —废弃',
  `appsecret` CHAR(32) NULL DEFAULT NULL COMMENT '微信相关 —废弃',
  `gamename` VARCHAR(45) NULL DEFAULT NULL,
  `initmoney` DOUBLE NULL DEFAULT NULL COMMENT '初始化赠送金币',
  `numberodd` DOUBLE NULL DEFAULT NULL COMMENT '数字赔率',
  `singleodd` DOUBLE NULL DEFAULT NULL COMMENT '下注单双的赔率',
  `bigodd` DOUBLE NULL DEFAULT NULL COMMENT '下注大小的赔率 — 暂时与下注单双赔率相同',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COMMENT = '系统设置表';


-- -----------------------------------------------------
-- Table `pk10`.`tokeninfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`tokeninfo` (
  `id` VARCHAR(100) NOT NULL,
  `tokenid` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `jsapitoken` VARCHAR(90) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '微信相关配置表 —弃用';


-- -----------------------------------------------------
-- Table `pk10`.`userbet`
-- -----------------------------------------------------
drop table if exists `pk10`.`userbet`;
CREATE TABLE IF NOT EXISTS `pk10`.`userbet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idnum` CHAR(14) NULL DEFAULT NULL COMMENT '下注期数',
  `type` VARCHAR(45) NULL DEFAULT NULL COMMENT '下注类型 ‘NUMBER’ ‘BIG_OR_SMALL’ ‘SINGLE_OR_DOUBLE’',
  `betmoney` INT(11) NULL DEFAULT NULL COMMENT '下注金额',
  `mulit` INT(11) NULL DEFAULT NULL COMMENT '倍率 此版本废弃',
  `betnum` VARCHAR(10) NULL DEFAULT NULL COMMENT '下注数字, 数字或者是 \'single\' \'double\' \'big\' \'small\' ',
  `createdAt` DATETIME NULL DEFAULT NULL,
  `userid` INT(11) NULL DEFAULT NULL COMMENT '用户id',
  `odds` DOUBLE NULL DEFAULT NULL COMMENT '赔率',
  `balance` INT(11) NULL DEFAULT '0' COMMENT '当前下注完之后的余额',
  `crashbalance` INT(11) NULL DEFAULT '0' COMMENT '兑奖后余额',
  `result` VARCHAR(45) NULL DEFAULT '未开奖' COMMENT '当前下注是否中奖 三种状态 未开奖 | 未中奖 | 中奖金额',
  `state` INT(1) NOT NULL DEFAULT '0' COMMENT '下注状态，1表示已兑奖 0 表示未兑奖',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8
COMMENT = '用户下注信息表';


-- -----------------------------------------------------
-- Table `pk10`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`userinfo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `openid` VARCHAR(255) NULL DEFAULT NULL COMMENT '微信相关属性 —废弃',
  `nickname` VARCHAR(255) NULL DEFAULT NULL COMMENT '微信昵称 — 废弃',
  `money` DOUBLE NULL DEFAULT NULL COMMENT '用户拥有金币',
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '用户注册时间',
  `tel` VARCHAR(21) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `isagent` INT(1) NULL DEFAULT '0' COMMENT '是否是代理商 或者管理员',
  `rebate` DOUBLE NULL DEFAULT NULL COMMENT '返点',
  `detail` VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  `owner` INT(11) NULL DEFAULT '0' COMMENT '此用户属于哪个代理商 默认为0 即不属于任何代理商',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8
COMMENT = '用户信息表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
