-- MySQL Script generated by MySQL Workbench
-- Wed Aug 31 23:52:45 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pk10
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pk10
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pk10` DEFAULT CHARACTER SET utf8 ;
USE `pk10` ;

-- -----------------------------------------------------
-- Table `pk10`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`goods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `goodname` VARCHAR(255) NULL DEFAULT NULL COMMENT '????',
  `price` FLOAT NULL DEFAULT NULL COMMENT '????',
  `goodsimg` VARCHAR(255) NULL DEFAULT NULL COMMENT '????',
  `goodsnum` INT(11) NULL DEFAULT NULL COMMENT '??????',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ucs2
COMMENT = '???';


-- -----------------------------------------------------
-- Table `pk10`.`lotteryhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`lotteryhistory` (
  `id` INT(11) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '????',
  `lotterynums` CHAR(29) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`notice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '??ID',
  `content` VARCHAR(12000) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '????',
  `title` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '????',
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '??????',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `pk10`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '??ID',
  `user` VARCHAR(255) CHARACTER SET 'ucs2' NULL DEFAULT NULL COMMENT '????',
  `price` DOUBLE NULL DEFAULT NULL COMMENT '????',
  `status` VARCHAR(45) CHARACTER SET 'ucs2' NULL DEFAULT NULL COMMENT '????',
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '??????',
  `userinfo_openid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_userinfo1_idx` (`userinfo_openid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '???';


-- -----------------------------------------------------
-- Table `pk10`.`orders_has_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`orders_has_goods` (
  `order_id` INT(11) NOT NULL,
  `goods_id` INT(11) NOT NULL,
  INDEX `fk_order_has_goods_goods1_idx` (`goods_id` ASC),
  INDEX `fk_order_has_goods_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_goods_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `pk10`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_goods_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `pk10`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`test` (
  `a` CHAR(1) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`tokenconfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`tokenconfig` (
  `tokenurl` VARCHAR(200) NULL DEFAULT NULL,
  `appid` CHAR(18) NOT NULL,
  `appsecret` CHAR(32) NULL DEFAULT NULL,
  `money` DOUBLE NULL DEFAULT NULL,
  `numberodd` DOUBLE NULL DEFAULT NULL,
  `singleodd` DOUBLE NULL DEFAULT NULL,
  `bigodd` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`appid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '?????';


-- -----------------------------------------------------
-- Table `pk10`.`tokeninfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`tokeninfo` (
  `id` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `tokenid` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `jsapitoken` VARCHAR(90) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci
COMMENT = '??token ?????????????????';


-- -----------------------------------------------------
-- Table `pk10`.`userbet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`userbet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idnum` CHAR(14) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL COMMENT '?????? ‘??’ ‘??’ ‘??’',
  `betmoney` DOUBLE NULL DEFAULT NULL COMMENT '????',
  `mulit` INT(11) NULL DEFAULT NULL COMMENT '????',
  `betnum` VARCHAR(10) NULL DEFAULT NULL COMMENT '????, ???? \'single\' \'double\' \'big\' \'small\' ',
  `createdAt` DATETIME NULL DEFAULT NULL,
  `userid` INT(11) NULL DEFAULT NULL,
  `odds` DOUBLE NULL DEFAULT NULL COMMENT '??',
  `state` INT(1) NOT NULL DEFAULT '0' COMMENT '?????1 ??????0?????',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 145
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`userinfo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `openid` VARCHAR(255) NULL DEFAULT NULL COMMENT '??????',
  `nickname` VARCHAR(255) NULL DEFAULT NULL COMMENT '????',
  `money` DOUBLE NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `tel` VARCHAR(21) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `isagent` INT(1) NULL DEFAULT 0 COMMENT '是否是代理商',
  `rebate` DOUBLE NULL COMMENT '返点',
  `ower` VARCHAR(45) NULL COMMENT '此用户属于哪个代理商',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`agent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `rebate` VARCHAR(45) NULL COMMENT '返点',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
